### ISSUE TITLE
404 Page Improvements

### ISSUE THREAD

**Issue by jzheaux** [spring-io/antora-ui-spring#210]
Spring's integration with Antora produces a 404 page whose recovery links focus on Spring Security, regardless of which project is being viewed.

For example:

1. Navigate to https://docs.spring.io/spring-ldap/reference/asdf.html and you will get a 404
2. Click the three horizontal dots on the left to find a set of recovery links
3. Notice that the focus seems to be on Spring Security and its set of published versions

While other projects appear on the left, it would be nice if this popup were either more generic or more directly focused on the documentation currently being visited (e.g. if I've navved to `/spring-ldap/**`, then I likely would be more helped by Spring LDAP links).

Additionally, there is an empty green box that could be more contextual as well; possibly it could point to the most recent documentation for that project.

**Comment by oodamien** [comment]
Fixed in https://github.com/spring-io/antora-ui-spring/pull/218

**Comment by philwebb** [comment]
I still see the old 404. Does Cloudflare need busting or is it something else? https://docs.spring.io/spring-boot/missing/

**Comment by oodamien** [comment]
It seems to be something else:
New 404: https://docs.spring.io/spring-boot/404.html
Old display: https://docs.spring.io/spring-security/404.html

**Comment by philwebb** [comment]
https://docs.spring.io/spring-missing/missing/ also fails. Perhaps it's the httpd config?

**Comment by oodamien** [comment]
Re-open on https://github.com/spring-io/antora-ui-spring/issues/225
